apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.deployment.yaml
  - backend.service.yaml
  - mongodb.deployment.yaml
  - mongodb.service.yaml

secretGenerator:
  - name: google-auth-secrets
    envs:
      - .auth.env