apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-backend
  labels:
    app: rust
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust
      tier: backend
  template:
    metadata:
      labels:
        app: rust
        tier: backend
    spec:
      initContainers:
      - name: init-db-ready
        image: mongo:4
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        command: ['/bin/sh', '-c']
        args:
          - echo "Waiting for mongodb at rust-mongodb:27017 to go live before the BE..."; 
          - until (mongo --host rust-mongodb:27017 >/dev/null) do echo "Waiting for connection for 2 sec."; sleep 2; done
      containers:
      - name: backend
        image: rust-backend
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: RUST_LOG
          value: "info"
        - name: DB_ADDR
          value: "rust-mongodb:27017"
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-auth-secrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-auth-secrets
              key: GOOGLE_CLIENT_SECRET
        - name: GOOGLE_REDIRECT_URI
          value: "http://localhost:4533/account/callback"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://signoz-otel-collector:4317"