apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - clickhouse.yaml

  - signoz.yaml

  - otel-collector.yaml

  - schema-migrator.yaml



configMapGenerator:

  - name: signoz-dashboards

    files:

      - service-metrics-dashboard.json
